### ISSUE TITLE
Problema link al simulatore

### ISSUE THREAD

**Issue by francescounitn** [Pater999/UNITN-lingprog-simulatore-mod2#9]
Da oggi 08/02/2024 il link non funziona, allego screenshot

<img width="960" alt="screenshot" src="https://github.com/Pater999/UNITN-lingprog-simulatore-mod2/assets/80281414/f06761ec-853c-46d7-b1ad-a05bc0954bd8">

**Comment by Pater999** [comment]
Risolto grazie!
